### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

### ISSUE THREAD

**Issue by taedori81** [django-oscar/django-oscar-avalara#7]
After installing django-oscar-avalara, I added to 'avalara' to INSTALLED_APPS and
Changed build_submission() and handle_successful_order()
I got these:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taedori/.virtualenvs/oscar-test/lib/python3.4/site-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/taedori/.virtualenvs/oscar-test/lib/python3.4/site-packages/django/core/management/**init**.py", line 312, in execute
    django.setup()
  File "/home/taedori/.virtualenvs/oscar-test/lib/python3.4/site-packages/django/**init**.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/taedori/.virtualenvs/oscar-test/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/taedori/.virtualenvs/oscar-test/lib/python3.4/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/home/taedori/.virtualenvs/oscar-test/lib/python3.4/importlib/**init**.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/taedori/.virtualenvs/oscar-test/lib/python3.4/site-packages/avalara/__init__.py", line 2, in <module>
    from .facade import *
  File "/home/taedori/.virtualenvs/oscar-test/lib/python3.4/site-packages/avalara/facade.py", line 18, in <module>
    OrderLine = get_model('order', 'Line')
  File "/home/taedori/.virtualenvs/oscar-test/lib/python3.4/site-packages/oscar/core/loading.py", line 235, in get_model
    return apps.get_model(app_label, model_name)
  File "/home/taedori/.virtualenvs/oscar-test/lib/python3.4/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/home/taedori/.virtualenvs/oscar-test/lib/python3.4/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

**Comment by dboone31** [comment]
Hey @taedori81, were you ever able to figure out a solution to this problem? I found the first comment [here](http://stackoverflow.com/a/25648427) to be helpful. Haven't had the chance to test it yet, but was curious if you found anything different.

**Comment by 1john** [comment]
@taedori81 @dboone31 was this ever resolved? same issue here

**Comment by 1john** [comment]
If anyone new drops in here and has this same issue. It's just a django version thing. The way this app tries to import things in __init__.py is no longer allowed. A lot of other things are outdated too, like the Avalara API endpoint it's trying to bounce off. I ended up using this as a starting place and making my own integration. Recommend doing the same.

**Comment by sasha0** [comment]
Initial issue is fixed.

@1john if you could list out what parts regarding Avalara API are outdated, in the separate issue, that will be highly appreciated. I could then go through them and fix.
